import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import { Header } from "@components/shared/header.component";
import { SubHeader } from "@/components/shared/sub-header.component";

import "@lib/assets/css/globals.css";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} antialiased`}
      >
        <Header />
        <SubHeader />
        {children}
      </body>
    </html>
  );
}
